### ISSUE TITLE
ModPacks?

### ISSUE THREAD

**Issue by Vastrix** [Myrathi/ChargePadsEx#10]
Are there any guidelines regarding modpacks? :)

**Comment by Myrathi** [comment]
The license is on the mod thread and there's a license file inside the jar (you can open it with WinZip or WinRAR directly).

You'll have problems using it with latest versions of IC2, though.

**Comment by Vastrix** [comment]
Ah yea, However i'm not a lawyer or anything..
Soo, Can we use the mod in a modpack? :)

(srry for bothering with this :s)

**Comment by Myrathi** [comment]
Please read the front page: https://github.com/Myrathi/ChargePadsEx#modpack-requests

At the bottom, there's a "ModPack Requests" section. Covers what you need to know.

**Comment by Vastrix** [comment]
Waw, now i feel all stupid :fearful: 
sorry, for wasting your time :s
