### ISSUE TITLE
Craft pads when reciepe blocked

### ISSUE THREAD

**Issue by ghost** [Myrathi/ChargePadsEx#5]
mod Recipier was blocked all reciepe in vanila/plugins/mods. But not blocked it on chardgepads.

mcpc+ 1.4.7
Recipier 1.3
ChargePads 2.5.0.72

**Comment by Myrathi** [comment]
I don't do anything weird by way of recipe registration: I use the base IC2 handler.
Also, that's a really old version that I really don't support any more (I don't even have an issue label for it). ;P
